[workspace]

members = ["ownership", "rectangle", "options", "communicator",
    "privacy", "containers", "traits", "largest", "lifetime", "awesome",
    "minigrep", "cacher", "box", "smart-ptr", "multithreading", "average-collection"]
